language: go
sudo: required
services:
  - docker

script:
  - docker run --rm -v "$PWD":/go/src/github.com/lileio/image_service -w /go/src/github.com/lileio/image_service lileio/go1.8-vips make ci

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make docker;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push lileio/image_service;
    fi
