version: '2'
services:
  cloud_storage:
    image: lileio/cloud_storage_service
    environment:
      - GOOGLE_STORAGE_BUCKET=cstesty
      - GOOGLE_STORAGE_PROJECT_ID=alex-b-159516
      - GOOGLE_STORAGE_LOCATION=eu
      - GOOGLE_APPLICATION_CREDENTIALS=/creds/google.json
    volumes:
      - ./data/creds:/creds
